In [26]:
import torch
import torch.nn as nn


#model class

In [27]:
#Simple one neuron
class Module(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear =nn.Linear(num_features,1)
    self.sigmoid =nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

##create dataset

In [28]:
features =torch.rand(10,5)

#create model
model =Module(features.shape[1])

#call model for forward pass
#model.forward_pass(features) #normal way
model(features)

tensor([[0.5046],
        [0.4984],
        [0.5257],
        [0.4401],
        [0.4545],
        [0.4812],
        [0.5307],
        [0.5028],
        [0.5160],
        [0.5476]], grad_fn=<SigmoidBackward0>)

In [29]:
model.linear.weight

Parameter containing:
tensor([[-0.1230, -0.1410,  0.2806, -0.2339,  0.2866]], requires_grad=True)

In [30]:
model.linear.bias

Parameter containing:
tensor([-0.0169], requires_grad=True)

In [31]:
!pip install torchinfo

In [32]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Module                                   [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

#Multiple layer

In [33]:
# more than one neuron
class Module(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear1 =nn.Linear(num_features,3)
    self.relu =nn.ReLU()
    self.linear2 =nn.Linear(3,1)
    self.sigmoid =nn.Sigmoid()

  def forward(self,features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)
    return out

In [34]:
features =torch.rand(10,5)

#create model
model =Module(features.shape[1])

#call model for forward pass
#model.forward_pass(features) #normal way
model(features)

tensor([[0.4875],
        [0.4808],
        [0.4753],
        [0.4841],
        [0.4983],
        [0.4755],
        [0.4913],
        [0.4966],
        [0.4883],
        [0.4823]], grad_fn=<SigmoidBackward0>)

In [35]:
model.linear1.weight

Parameter containing:
tensor([[-3.6390e-01, -3.6011e-01, -3.9920e-01, -2.5574e-01,  3.2167e-01],
        [-4.0147e-01, -1.8839e-01,  4.1850e-05,  2.0039e-01,  1.5523e-01],
        [ 3.6084e-01, -3.0900e-03,  3.6301e-02,  1.9604e-01, -3.3572e-01]],
       requires_grad=True)

In [36]:
model.linear2.weight

Parameter containing:
tensor([[ 0.3720,  0.2346, -0.0612]], requires_grad=True)

In [37]:
model.linear1.bias

Parameter containing:
tensor([-0.4007,  0.3952, -0.2504], requires_grad=True)

In [38]:
model.linear2.bias

Parameter containing:
tensor([-0.1148], requires_grad=True)

In [39]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Module                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

#creating sequential

In [40]:
class Module(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network =nn.Sequential(

        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out = self.network(features)
    return out

In [41]:
features =torch.rand(10,5)

#create model
model =Module(features.shape[1])

#call model for forward pass
#model.forward_pass(features) #normal way
model(features)

tensor([[0.3581],
        [0.3886],
        [0.3619],
        [0.3614],
        [0.3772],
        [0.3445],
        [0.3592],
        [0.3003],
        [0.3414],
        [0.3261]], grad_fn=<SigmoidBackward0>)

In [42]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Module                                   [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00