In [ ]:
pip install torch torchvision torchaudio

In [ ]:
import torch
print(torch.__version__)

2.11.0+cu128


In [ ]:
if torch.cuda.is_available():
        print("GPU available")
        print("Number of GPUs available:", torch.cuda.device_count())
        print(torch.cuda.get_device_name(0))
else:
        print("No GPU available")


GPU available
Number of GPUs available: 1
Tesla T4


In [ ]:
#CREATING TENSORS

In [ ]:
#using empty

a =torch.empty(3,4)

In [ ]:
#type
type(a)

torch.Tensor

In [ ]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(5,8)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
torch.rand(7,8)

tensor([[0.7981, 0.5127, 0.3304, 0.4278, 0.9980, 0.6065, 0.8801, 0.4154],
        [0.8755, 0.4667, 0.6990, 0.2676, 0.9291, 0.8050, 0.9665, 0.8495],
        [0.7475, 0.6806, 0.6020, 0.9208, 0.3718, 0.4990, 0.6860, 0.5278],
        [0.2210, 0.8835, 0.0301, 0.8995, 0.3508, 0.7753, 0.1354, 0.2193],
        [0.7297, 0.8199, 0.2430, 0.9547, 0.8720, 0.2287, 0.0891, 0.7945],
        [0.1938, 0.3543, 0.4892, 0.2081, 0.7516, 0.1250, 0.9424, 0.7865],
        [0.7670, 0.0865, 0.4894, 0.6094, 0.2041, 0.0036, 0.2896, 0.1963]])

In [ ]:
# using seed
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
#dtype

torch.tensor([2.3,5.6,8.9],dtype=torch.int32)

tensor([2, 5, 8], dtype=torch.int32)

In [ ]:
#tensor operations
b=torch.tensor([3,5,6])
c=torch.tensor([8,7,2])

print(b+c)

tensor([11, 12,  8])


In [ ]:
print(b-c)

tensor([-5, -2,  4])


In [ ]:
print(b/c)

tensor([0.3750, 0.7143, 3.0000])


In [ ]:
print(b//c)

tensor([0, 0, 3])


In [ ]:
d =torch.tensor([6.99,8.00,3.88])
d.round()


tensor([7., 8., 4.])

In [ ]:
d.ceil()

tensor([7., 8., 4.])

In [ ]:
d.floor()

tensor([6., 8., 3.])

In [ ]:
torch.clamp(d,min=2,max=7)

tensor([6.9900, 7.0000, 3.8800])

In [ ]:
e =torch.tensor([[2,4,5,6],[3,6,4,8]])

In [ ]:
torch.sum(e)

tensor(38)

In [ ]:
torch.argmax(e)

tensor(7)

In [ ]:
torch.argmin(e)

tensor(0)

In [ ]:
#matrix operations

In [ ]:
f =torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[0, 4, 0],
        [3, 8, 4]])
tensor([[0, 4],
        [1, 2],
        [5, 5]])


In [ ]:
torch.matmul(f,g)

tensor([[ 4,  8],
        [28, 48]])

In [ ]:
torch.dot(torch.tensor([2,3]),torch.tensor([4,5]))

tensor(23)

In [ ]:
f = torch.tensor([1, 2, 3])
g = torch.tensor([0, 2, 4])

print(f > g)

tensor([ True, False, False])


In [ ]:
print(f == g)

tensor([False,  True, False])


In [ ]:
print(f != g)

tensor([ True, False,  True])


In [ ]:
torch.sqrt(f)

tensor([1.0000, 1.4142, 1.7321])

In [ ]:
a =torch.tensor([9,4,5])
b =a

In [ ]:
b

tensor([9, 4, 5])

In [ ]:
a[0]=4

In [ ]:
b

tensor([4, 4, 5])

In [ ]:
print(id(a))
id(b)

137616192562080


137616192562080

In [ ]:
c =a.clone()

In [ ]:
print(id(a))
id(c)

137616192562080


137616137000256

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device =torch.device('cuda')

In [ ]:
torch.rand((2,3),device=device)

tensor([[0.6130, 0.0101, 0.3984],
        [0.0403, 0.1563, 0.4825]], device='cuda:0')

In [ ]:
b

tensor([4, 4, 5])

In [ ]:
b.to(device)

tensor([4, 4, 5], device='cuda:0')

In [ ]:
b+5

tensor([ 9,  9, 10])